### ISSUE TITLE
Meaning of parameters in cfg/params.yml

### ISSUE THREAD

**Issue by Celinna** [AerialRobotics-IITK/helipad_det#1]
What do the parameters a, b, c, d mean? I have read the paper mentioned in the readme, but I did not find mentions of them. Additionally, I assume the parameters r is the radius of the circle, but what is it unit?

**Comment by ashwin2802** [comment]
Hello @Celinna! Thank you for your interest in our work.

r, a, b, c, d are scale invariant parameters that are used to match the helipad signature.

r is the ratio of the radii of the two concentric circles (outer by inner).

a, b, c, d are the ratio of the each of different segments of the H (each of different length) to the total length of the H contour.

Since these are ratios, they have no units.

An example calculation of these parameters (with the figure from the cited paper)

![image](https://user-images.githubusercontent.com/45398493/158237051-c92b4b6e-8097-478d-a2cf-16a9d0826e02.png)

r would be R_0 / r_0 = 5x / 4x = 1.25      (the helipad we used had r=1.2)

The total length of the H contour would be 5x * 2 + 1x * 4 + 2x * 4 + 2x * 2 = 26x

So, the four parameters (for each segment of different length)

a = 5x / 26x = 5 / 26 = 0.1923
b = 1x / 26x = 2 / 26 = 0.0384
c = 2x / 26x = 0.0769
d = 2x / 26x = 0.0769

Hope this helps!

**Comment by Celinna** [comment]
@ashwin2802 Thank you for clarifying! The values makes sense now.
